import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import AuthProvider from "@/providers/SessionProvider";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { useEffect } from "react";

export default function RootLayout({ children }: { children: React.ReactNode }) {

  


  return (
    <html lang="en">
      <body className="font-poppins">
        <AuthProvider>
          <QueryProvider>
            <main className={` ${poppins.variable}`}>{children}</main>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
